[package]
name = "set_1_3_one_xor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-tools.workspace = true
hex-literal = "0.4.1"
lingua = "1.4.0"
hex = "0.4.3"